spring:
  application:
    name: microservice-classification
  
  # 데이터베이스 설정 (환경변수에서 가져옴)
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: ${WEBSITES_PORT:8080}

# OpenAI API 설정
openai:
  api-key: ${OPENAI_API_KEY}
  model: ${OPENAI_MODEL:gpt-4o-mini}

# 외부 API 설정
external:
  admin-api:
    base-url: ${ADMIN_API_BASE_URL}
  dashboard-api:
    base-url: ${DASHBOARD_API_BASE_URL}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.hanacard: ${LOGGING_LEVEL_COM_HANACARD:DEBUG}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"