spring:
  application:
    name: microservice-classification

server:
  port: ${PORT:8080}

logging:
  level:
    com.hanacard: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"